[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_SITE_URL = "https://tranquilthug.netlify.app"
  NODE_VERSION = "18"

[[redirects]]
  from = "/collaborate"
  to = "/lease-your-property"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
